### ISSUE TITLE
Fix Ecotype branching before reaching X = 0

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#130]
Ecotype is not supposed to branch before it reaches it's optimum, right...?

**Comment by Lumphie** [comment]
![kewe_gui4](https://cloud.githubusercontent.com/assets/21882358/21259904/e58498d2-c383-11e6-8903-851197dbb8e0.png)

This time it's the female preference and the male trait acting weird.

**Comment by Lumphie** [comment]
Looked more into Sander's paper. Preference and male trait should act like this, They will hover around the ecotype, but will go back to 0 when ecotype is stable, should be fine. Might want to keep an eye on it though.

**Comment by Lumphie** [comment]
Whoops. Not closing it yet. Ecotype is still branching. Might be fixed when 2 species in 1 populations will be stable.

**Comment by richelbilderbeek** [comment]
With lower mutation rate and more extreme initial ecological trait, ecotype may be considered branching before reaching an average trait value of 0.0.

![quick_branching](https://cloud.githubusercontent.com/assets/2098230/25804644/024bd75c-33fd-11e7-944a-bebf46c92800.png)

Because of low priority of this Issue, I will close this for now.

**Comment by richelbilderbeek** [comment]
OTOH, there is a stronger effect after mean ecological trait has reached an average of zero.
