### ISSUE TITLE
munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#81]
Marked with `FIX_ISSUE_81`

**Comment by richelbilderbeek** [comment]
I read that for a `std::vector<double> v`, this error may be caused by `v[i]` for `i` being less than zero or i being equal or bigger than the size of `v`.

I added some `assert`s, found an invalid index. 

@Lumphie: I suggest you fix those first. 

I propose, if the error still remains:
 * you add some more `assert` for index operators and fix those errors
 * after this, let me know and I'll step back in

**Comment by Lumphie** [comment]
Fixed
